### ISSUE TITLE
commands/setup.js 71번째 줄, 정규식 체크로 바꿔주시길 바랍니다.

### ISSUE THREAD

**Issue by hjunhuh** [mswgen/diko.ml#1]
d!setup ./style.css
d!setup /style.css
d!setup //style.css

와 같은 문자열은 https://diko.ml/style.css 으로 리다이렉트 됩니다.
string.match() 함수로 코드 변경 부탁드립니다.

**Comment by hjunhuh** [comment]
https://diko.ml/%2F%2F%2Fstatic%2Findex.html 
d!setup ///static/index.html
이런것도 가능하네요..

**Comment by dropdb220** [comment]
혹시 디스코드 태그와 id가 어떻게 되나요?
그나저나 이번주 토요일에 컴퓨터를 할 수 있어서 그때 수정할게요.

**Comment by dropdb220** [comment]
제가 실력이 안돼서;;; 일단 string.includes()로 했어요
이슈 닫을게여
